# Use root/example as user/password credentials
version: '3.1'

services:
  ecctrl:
    image: ecctrl
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    restart: always
    volumes:
      - ./:/usr/src/app
    ports:
      - "3001:5173"
  theia:
    image: elswork/theia
    restart: always
    ports:
      - 3031:3000
    volumes:
      - .:/home/project:cached
